# Generated by Django 4.1.1 on 2022-10-06 10:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CV",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Education",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("school", models.CharField(blank=True, max_length=500, null=True)),
                (
                    "specialization",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("scores", models.CharField(blank=True, max_length=500, null=True)),
                ("start_date", models.CharField(blank=True, max_length=500, null=True)),
                ("end_date", models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                "verbose_name_plural": "Education",
            },
        ),
        migrations.CreateModel(
            name="Experience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company", models.CharField(blank=True, max_length=500, null=True)),
                ("position", models.CharField(blank=True, max_length=500, null=True)),
                ("start_date", models.CharField(blank=True, max_length=500, null=True)),
                ("end_date", models.CharField(blank=True, max_length=500, null=True)),
                ("description", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name_plural": "Experiences",
            },
        ),
        migrations.CreateModel(
            name="Showcase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=500, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("url", models.CharField(blank=True, max_length=500, null=True)),
                ("start_date", models.CharField(blank=True, max_length=500, null=True)),
                ("end_date", models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                "verbose_name_plural": "Projects",
            },
        ),
        migrations.CreateModel(
            name="Theme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("path", models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Volunteer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "organization",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("position", models.CharField(blank=True, max_length=500, null=True)),
                ("start_date", models.CharField(blank=True, max_length=500, null=True)),
                ("end_date", models.CharField(blank=True, max_length=500, null=True)),
                ("description", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name_plural": "Volunteers",
            },
        ),
        migrations.CreateModel(
            name="VolunteerSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cv",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="CVs.cv"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Volunteer sections",
            },
        ),
        migrations.CreateModel(
            name="VolunteerBullet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bullet", models.TextField(blank=True, null=True)),
                (
                    "volunteer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="volunteer_bullets",
                        to="CVs.volunteer",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Volunteer bullets",
            },
        ),
        migrations.AddField(
            model_name="volunteer",
            name="volunteer_section",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="volunteers",
                to="CVs.volunteersection",
            ),
        ),
        migrations.CreateModel(
            name="Summary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("summary", models.TextField(blank=True, null=True)),
                (
                    "cv",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="CVs.cv"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Summaries",
            },
        ),
        migrations.CreateModel(
            name="SoftSkillSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cv",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="CVs.cv"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Soft skill sections",
            },
        ),
        migrations.CreateModel(
            name="SoftSkill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("soft_skill", models.CharField(blank=True, max_length=500, null=True)),
                (
                    "soft_skill_section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="soft_skills",
                        to="CVs.softskillsection",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Soft skills",
            },
        ),
        migrations.CreateModel(
            name="SocialLinkSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cv",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="CVs.cv"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Social link sections",
            },
        ),
        migrations.CreateModel(
            name="SocialLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=500, null=True)),
                ("url", models.CharField(blank=True, max_length=500, null=True)),
                (
                    "social_link_section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="social_links",
                        to="CVs.sociallinksection",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Social links",
            },
        ),
        migrations.CreateModel(
            name="ShowcaseSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cv",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="CVs.cv"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "ShowcaseSections",
            },
        ),
        migrations.CreateModel(
            name="ShowcaseBullet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bullet", models.TextField(blank=True, null=True)),
                (
                    "showcase",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="showcase_bullets",
                        to="CVs.showcase",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Project bullets",
            },
        ),
        migrations.AddField(
            model_name="showcase",
            name="showcase_section",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="showcases",
                to="CVs.showcasesection",
            ),
        ),
        migrations.CreateModel(
            name="ProfessionalSkillSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cv",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="CVs.cv"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Professional Skill sections",
            },
        ),
        migrations.CreateModel(
            name="ProfessionalSkill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("skills", models.CharField(blank=True, max_length=500, null=True)),
                (
                    "professional_skill_section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="professional_skills",
                        to="CVs.professionalskillsection",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Professional skills",
            },
        ),
        migrations.CreateModel(
            name="LanguageSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cv",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="CVs.cv"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Language sections",
            },
        ),
        migrations.CreateModel(
            name="Language",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("language", models.CharField(blank=True, max_length=500, null=True)),
                ("level", models.CharField(blank=True, max_length=500, null=True)),
                (
                    "language_section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="languages",
                        to="CVs.languagesection",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Languages",
            },
        ),
        migrations.CreateModel(
            name="InterestSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cv",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="CVs.cv"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Interest sections",
            },
        ),
        migrations.CreateModel(
            name="Interest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("interest", models.CharField(blank=True, max_length=500, null=True)),
                (
                    "interest_section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interests",
                        to="CVs.interestsection",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Interests",
            },
        ),
        migrations.CreateModel(
            name="Header",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("job_title", models.CharField(blank=True, max_length=255, null=True)),
                ("email", models.CharField(blank=True, max_length=500, null=True)),
                ("phone", models.CharField(blank=True, max_length=500, null=True)),
                ("address", models.CharField(blank=True, max_length=500, null=True)),
                ("url_link", models.CharField(blank=True, max_length=500, null=True)),
                (
                    "cv",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="CVs.cv"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Headers",
            },
        ),
        migrations.CreateModel(
            name="ExperienceSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cv",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="CVs.cv"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "ExperienceSections",
            },
        ),
        migrations.CreateModel(
            name="ExperienceBullet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bullet", models.TextField(blank=True, null=True)),
                (
                    "experience",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="experience_bullets",
                        to="CVs.experience",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Job bullets",
            },
        ),
        migrations.AddField(
            model_name="experience",
            name="experience_section",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="experiences",
                to="CVs.experiencesection",
            ),
        ),
        migrations.CreateModel(
            name="EducationSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cv",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="CVs.cv"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "EducationSections",
            },
        ),
        migrations.CreateModel(
            name="EducationBullet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bullet", models.TextField(blank=True, null=True)),
                (
                    "education",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="education_bullets",
                        to="CVs.education",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Education bullets",
            },
        ),
        migrations.AddField(
            model_name="education",
            name="education_section",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="educations",
                to="CVs.educationsection",
            ),
        ),
        migrations.AddField(
            model_name="cv",
            name="cv_themes",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="CVs.theme",
            ),
        ),
        migrations.AddField(
            model_name="cv",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
