# Generated by Django 4.1.1 on 2022-10-25 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("CVs", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="professionalskill",
            old_name="skills",
            new_name="skill",
        ),
    ]
