# Generated by Django 4.1.1 on 2022-11-05 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("CVs", "0002_rename_skills_professionalskill_skill"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="experiencebullet",
            options={"verbose_name_plural": "Experience bullets"},
        ),
        migrations.AlterField(
            model_name="header",
            name="cv",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="header",
                to="CVs.cv",
            ),
        ),
    ]
