# Generated by Django 4.1.1 on 2022-11-05 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("CVs", "0003_alter_experiencebullet_options_alter_header_cv"),
    ]

    operations = [
        migrations.AlterField(
            model_name="educationsection",
            name="cv",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="education_section",
                to="CVs.cv",
            ),
        ),
        migrations.AlterField(
            model_name="experiencesection",
            name="cv",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="experience_section",
                to="CVs.cv",
            ),
        ),
        migrations.AlterField(
            model_name="interestsection",
            name="cv",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="interest_section",
                to="CVs.cv",
            ),
        ),
        migrations.AlterField(
            model_name="languagesection",
            name="cv",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="language_section",
                to="CVs.cv",
            ),
        ),
        migrations.AlterField(
            model_name="professionalskillsection",
            name="cv",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="professional_skill_section",
                to="CVs.cv",
            ),
        ),
        migrations.AlterField(
            model_name="showcasesection",
            name="cv",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="showcase_section",
                to="CVs.cv",
            ),
        ),
        migrations.AlterField(
            model_name="sociallinksection",
            name="cv",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="social_link_section",
                to="CVs.cv",
            ),
        ),
        migrations.AlterField(
            model_name="softskillsection",
            name="cv",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="soft_skill_section",
                to="CVs.cv",
            ),
        ),
        migrations.AlterField(
            model_name="summary",
            name="cv",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="summary",
                to="CVs.cv",
            ),
        ),
        migrations.AlterField(
            model_name="volunteersection",
            name="cv",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="volunteer_section",
                to="CVs.cv",
            ),
        ),
    ]
