# Generated by Django 4.1.1 on 2022-11-05 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("CVs", "0004_alter_educationsection_cv_alter_experiencesection_cv_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="experience",
            name="experience_section",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="experience",
                to="CVs.experiencesection",
            ),
        ),
    ]
