# Generated by Django 4.1.1 on 2023-01-18 08:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("CVs", "0006_alter_experience_experience_section"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cv",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cvs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
